Name:           ros-kinetic-smach
Version:        2.0.1
Release:        0%{?dist}
Summary:        ROS smach package

Group:          Development/Libraries
License:        BSD
Source0:        %{name}-%{version}.tar.gz

BuildRequires:  ros-kinetic-catkin

%description
SMACH is a task-level architecture for rapidly creating complex robot behavior.
At its core, SMACH is a ROS-independent Python library to build hierarchical
state machines. SMACH is a new library that takes advantage of very old concepts
in order to quickly create robust robot behavior with maintainable and modular
code.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/kinetic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/kinetic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/kinetic

%changelog
* Thu Jun 08 2017 Isaac I. Y. Saito <gm130s@gmail.com> - 2.0.1-0
- Autogenerated by Bloom

* Mon Apr 25 2016 Jonathan Bohren <jbo@jhu.edu> - 2.0.0-2
- Autogenerated by Bloom

* Mon Apr 25 2016 Jonathan Bohren <jbo@jhu.edu> - 2.0.0-1
- Autogenerated by Bloom

* Mon Apr 25 2016 Jonathan Bohren <jbo@jhu.edu> - 2.0.0-0
- Autogenerated by Bloom

